
package services;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Facade", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Facade {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchTelephone", targetNamespace = "http://service/", className = "services.SearchTelephone")
    @ResponseWrapper(localName = "searchTelephoneResponse", targetNamespace = "http://service/", className = "services.SearchTelephoneResponse")
    @Action(input = "http://service/Facade/searchTelephoneRequest", output = "http://service/Facade/searchTelephoneResponse")
    public String searchTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns services.Personne
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchPersonne", targetNamespace = "http://service/", className = "services.SearchPersonne")
    @ResponseWrapper(localName = "searchPersonneResponse", targetNamespace = "http://service/", className = "services.SearchPersonneResponse")
    @Action(input = "http://service/Facade/searchPersonneRequest", output = "http://service/Facade/searchPersonneResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://service/Facade/searchPersonne/Fault/Exception")
    })
    public Personne searchPersonne(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addPersonne", targetNamespace = "http://service/", className = "services.AddPersonne")
    @ResponseWrapper(localName = "addPersonneResponse", targetNamespace = "http://service/", className = "services.AddPersonneResponse")
    @Action(input = "http://service/Facade/addPersonneRequest", output = "http://service/Facade/addPersonneResponse")
    public void addPersonne(
        @WebParam(name = "arg0", targetNamespace = "")
        Personne arg0);

    /**
     * 
     * @param tel
     * @param nom
     * @param prenom
     */
    @WebMethod
    @RequestWrapper(localName = "ajouterPersonneTel", targetNamespace = "http://service/", className = "services.AjouterPersonneTel")
    @ResponseWrapper(localName = "ajouterPersonneTelResponse", targetNamespace = "http://service/", className = "services.AjouterPersonneTelResponse")
    @Action(input = "http://service/Facade/ajouterPersonneTelRequest", output = "http://service/Facade/ajouterPersonneTelResponse")
    public void ajouterPersonneTel(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "tel", targetNamespace = "")
        String tel);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllNom", targetNamespace = "http://service/", className = "services.GetAllNom")
    @ResponseWrapper(localName = "getAllNomResponse", targetNamespace = "http://service/", className = "services.GetAllNomResponse")
    @Action(input = "http://service/Facade/getAllNomRequest", output = "http://service/Facade/getAllNomResponse")
    public List<String> getAllNom();

}
